### ISSUE TITLE
How was YOUR weekend?

### ISSUE THREAD

**Issue by passy** [robbbz/ama#11]
:smiley:

**Comment by robbbz** [comment]
Pretty terrible. I spend most of it on a plane and on airports.

Friday morning I arrived at airport and my flight was 5 hours delayed. Not worth it to drive home again, so I stayed there spending most of my time going from coffeeshop to coffeeshop. The first two were fun, others rest weren't. Had some time to catch up on some series though. Finally, 2PM (7 hours later...) we're able to board. Couldn't sleep on the plane (I never do) so ended up watching a bunch of movies. Seen the martian, tomorrowland, Jurrasic World, Ant-man and Jaws. Also emptied my podcatcher and learned a bunch about Electron. We finally arrive around 3AM, I'm terribly sleepy and turns out there's a problem with out plane's documents. Seriously thanks, American Airlines. Resulting in 1.5 hours waiting. :smiling_imp: 

And when I finally thought about getting to my bed (the sun was rising already...) someone at my company decided to fuck something up with the booking of my hotel. Needed to wake someone up to get everything sorted out. 

Then saturday was the longest meeting ever (might be because I slept 3 hours and a bit). And when it finally ends I drop my coke on an expensive carpet. Sunday and monday were also pretty boring and now I'm about to go the airport again. Any movie recommendations for on the plane, by the way?
